### ISSUE TITLE
Notice: Undefined variable: region_id

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/copy_blocks#1]
Seeing this in the logs on a site that I'm testing this module on:

> Notice: Undefined variable: region_id in BlockRegionCopy->getContent() (line 47 of /home/public_html/modules/copy_blocks/block.region_copy.inc).

**Comment by herbdool** [comment]
@docwilmot need a new release after this fix?

**Comment by docwilmot** [comment]
Thanks
