### ISSUE TITLE
Make select dropdown easier to read

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/copy_blocks#10]
Just testing this module for the first time and I found the select list of blocks/regions to be a mass of words that was difficult to read and find what I was looking for. 

![Home_page__home____Test_One_and_Pages___Simplo](https://user-images.githubusercontent.com/3144571/90078837-b87ea200-dccb-11ea-8e18-b3088f48e368.png)

The suggestion by @laryn does sound good, but I don't know how to write a PR for that. 

I can make a PR with some small changes that MIGHT be a marginal improvement for now. Basically, I am just recommending brackets to break apart the elements in the list. 

![Home_page__home____Simplo_and_Pages___Simplo_and_New_Issue_·_backdrop-contrib_copy_blocks](https://user-images.githubusercontent.com/3144571/90078899-ef54b800-dccb-11ea-825c-ace6ec082eeb.png)

**Comment by stpaultim** [comment]
For regions:

**CURRENT**

![Home_page__home____Test_One_and_Make_select_dropdown_easier_to_read_·_Issue__10_·_backdrop-contrib_copy_blocks](https://user-images.githubusercontent.com/3144571/90079001-49ee1400-dccc-11ea-995b-14a04398a07f.png)

**Maybe a LITTLE better in PR?** - I put the layout first, because they are already grouped that way and it's easier to scan the list this way (in my opinion). 

![Home_page__home____Simplo_and_Make_select_dropdown_easier_to_read_·_Issue__10_·_backdrop-contrib_copy_blocks](https://user-images.githubusercontent.com/3144571/90079073-7dc93980-dccc-11ea-8a35-8954aac16e71.png)

**Comment by ghost** [comment]
I'd suggest something like what we're doing in https://github.com/backdrop/backdrop-issues/issues/4481: ![image](https://user-images.githubusercontent.com/2423362/87416076-d5458e00-c5d6-11ea-9509-deba1fbfe23b.png)

I.e. different font colour/size (or is that not possible in a select list?)
Or maybe this should be an autocomplete anyway...

**Comment by stpaultim** [comment]
Happy for ideas to make this better. I'm willing to work on it more if anyone has a good suggestion.

**Comment by stpaultim** [comment]
@BWPanda - Thanks. I'll take a look at that code! Good idea!

**Comment by docwilmot** [comment]
OK I'll tackle https://github.com/backdrop-contrib/copy_blocks/issues/8.

**Comment by stpaultim** [comment]
Well, that might be good. I tried styling a select element and am not sure how. 

I found this: https://stackoverflow.com/questions/7208786/how-to-style-the-option-of-an-html-select-element

**Comment by ghost** [comment]
It looks like https://github.com/backdrop-contrib/copy_blocks/issues/8 has already been implemented which, IMO, is a better solution anyway. Closing this issue in favour of that one.
