### ISSUE TITLE
Ship with 'naked' block template

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/copy_blocks#14]
An unfortunate consequence of having a region contained within a block, is that you get the containing block's markup surrounding the region. This may cause issues with the styling.

I recommend either:

- Overriding the default `block.tpl.php` template with a 'naked' version that just outputs the block's content without any surrounding markup, or
- Shipping with this template, but not having it enabled by default, and just including instructions for how users can enable it themselves.

**Comment by ghost** [comment]
As an example, here's what my default layout's sidebar looks like:

![image](https://user-images.githubusercontent.com/2385329/101000573-35eb5c80-35b2-11eb-9450-78f5c033270a.png)

(i.e. sidebar > inner > bunch of blocks)

But here's what my other layout's sidebar looks like (when using a region copy block):

![image](https://user-images.githubusercontent.com/2385329/101000800-764ada80-35b2-11eb-8bec-29a1897398ab.png)

(i.e. sidebar > inner > block-region-copy > block-inner > bunch of blocks)

**Comment by docwilmot** [comment]
Added an option on the block configure form for this. Hope it helps.
