### ISSUE TITLE
Different block copy blocks are indistinguishable

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/copy_blocks#17]
I've added a few custom blocks to my default layout. I then made copies of those blocks in a different layout. In the different layout the styling of those blocks isn't showing. I understand that this is because the block name/class has changed, so I go to get the new names/classes so I can add them to my stylesheet. But all the 'copy blocks' have the exact same classes, so I can't distinguish them:

![image](https://user-images.githubusercontent.com/2385329/101001574-697ab680-35b3-11eb-9e84-d624de42ac8a.png)

These are 3 different blocks, but they all have the same class (because they're all 'block copy' blocks).

We need to add a class that references the original block being copied so we know what they all are and can style them differently.

**Comment by ghost** [comment]
Workaround is to manually add a new class to each block copy via the Layouts UI, but I think this should be automated if possible...

**Comment by docwilmot** [comment]
Should be fixed
