### ISSUE TITLE
Notice: Undefined property: BlockCopy::$parent_block in BlockCopy->getTitle() (line 31

### ISSUE THREAD

**Issue by kreynen** [backdrop-contrib/copy_blocks#5]
This is still an issue after https://github.com/backdrop-contrib/copy_blocks/issues/3

I'm a little confused by https://github.com/backdrop-contrib/copy_blocks/blob/1.x-1.x/block.block_copy.inc#L31

Why are we checking to see if $parent_block->settings['title'] and then returning $this->parent_block['title']

I'm testing with the "Powered by Backdrop".  Adding a 2nd instance of block to the footer region results in this error regardless of whether the parent block's title is set to Default, Custom or None.

**Comment by docwilmot** [comment]
doesnt make sense does it? :smile: 
if you push a PR i'd be happy. thanks.

**Comment by docwilmot** [comment]
Fixed in latest release, thanks
