### ISSUE TITLE
Visibility conditions on copied blocks aren't respected

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/copy_blocks#7]
I'm trying to do further testing, but it's looking like when I copy a region to another layout, the visibility conditions on the copied blocks are not being applied. (All blocks show up regardless of the visibility conditions I've set).

**Comment by laryn** [comment]
Confirmed on a sandbox.

**Comment by laryn** [comment]
Also it seems that if the Layout being copied from is disabled, the blocks still show up in the copy. I'm not sure if that should be the case.

**Comment by laryn** [comment]
@docwilmot Does this seem reasonable? 

https://github.com/backdrop-contrib/copy_blocks/pull/9

It seems to solve things in my current site in terms of visibility conditions on blocks carrying through to the copied region (although not with disabled layout regions still being copied/pulled in -- but maybe that's a feature, not a bug).

**Comment by docwilmot** [comment]
> Also it seems that if the Layout being copied from is disabled, the blocks still show up in the copy. I'm not sure if that should be the case.

I dont think there are rules re this, we'd need to decide how we want it to work. And I'd say blocks should be separate from layouts, so a block should still be available in another region if its disabled elsewhere. So in short I think this is OK.

**Comment by docwilmot** [comment]
Merged https://github.com/backdrop-contrib/copy_blocks/pull/9
Thanks
